/**
 * @freshgum/typedi <https://github.com/freshgum-bubbles/typedi>
 *
 * @license MIT
 * Copyright (c) 2015-2021 TypeStack
 * Copyright (c) 2023-2024 freshgum (https://github.com/freshgum-bubbles)
 * For a full copy of the license, see the LICENSE file in the root folder.
 */

export * from '../index.mjs';

// Export all entries from the contrib/ barrel file generated by Rollup at build time.
// See <scripts/rollup/generateWebBuildEntryPoints.mjs> for more information.
export * as Contrib from 'internal:web_entry_contrib_barrel_do_not_use';
